FROM ubuntu

RUN apt-get -y update && echo '2021-02-05'
RUN apt -y install software-properties-common && add-apt-repository ppa:ondrej/php && apt-get update
RUN apt -y install php8.0
RUN apt -y install php8.0-mysql
RUN apt-get -y install php8.0-xml
RUN apt-get -y install php8.0-mbstring

#
# Install composer
#
RUN php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');" && \
php composer-setup.php --install-dir=/usr/local/bin  --filename=composer && \
php -r "unlink('composer-setup.php');"

#
# Install required packages
#
RUN apt-get -y install zip unzip

#
# Code Coverage
#
RUN apt-get -y install php8.0-xdebug
RUN echo xdebug.mode=coverage >> /etc/php/8.0/cli/conf.d/20-xdebug.ini

